<!-- Sidebar -->
<ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

<!-- Sidebar - Brand -->
<a class="sidebar-brand d-flex align-items-center justify-content-center" href="/KumbiaPHP1/">
    <div class="sidebar-brand-icon">
        <i class="fas fa-home fa-fw"></i>
    </div>
    <div class="sidebar-brand-text mx-3">SAKILA</div>
</a>

<!-- Divider -->
<hr class="sidebar-divider my-0">
<!-- Nav Item - Pages Collapse Menu -->
    <li class="nav-item active">
        <a class="nav-link" href="#" data-toggle="collapse" data-target="#collapsePages" aria-expanded="false"
           aria-controls="collapsePages">
            <i class="fas fa-fw fa-folder"></i>
            <span>Actor</span>
        </a>
        <div id="collapsePages" class="collapse" aria-labelledby="headingPages" data-parent="#accordionSidebar">
            <div class="bg-white py-2 collapse-inner rounded">
                <h6 class="collapse-header">Login Actor:</h6>
                <a class="collapse-item" href="/KumbiaPHP1/actor">Actor</a>
                <a class="collapse-item" href="/KumbiaPHP1/actor_info">Actor info</a>
            </div>
        </div>
    </li>

    <!-- Nav Item - Pages Collapse Menu -->
    <li class="nav-item active">
        <a class="nav-link" href="#" data-toggle="collapse" data-target="#collapsePages2" aria-expanded="false"
           aria-controls="collapsePages2">
            <i class="fas fa-fw fa-folder"></i>
            <span>Address</span>
        </a>
        <div id="collapsePages2" class="collapse" aria-labelledby="headingPages"
             data-parent="#accordionSidebar">
            <div class="bg-white py-2 collapse-inner rounded">
                <h6 class="collapse-header">Login Address:</h6>
                <a class="collapse-item" href="/KumbiaPHP1/city">City</a>
                <a class="collapse-item" href="/KumbiaPHP1/country">Country</a>
            </div>
        </div>
    </li>

    <!-- Nav Item - Pages Collapse Menu -->
    <li class="nav-item active">
        <a class="nav-link" href="#" data-toggle="collapse" data-target="#collapsePages3" aria-expanded="false"
           aria-controls="collapsePages3">
            <i class="fas fa-fw fa-folder"></i>
            <span>Customer</span>
        </a>
        <div id="collapsePages3" class="collapse" aria-labelledby="headingPages"
             data-parent="#accordionSidebar">
            <div class="bg-white py-2 collapse-inner rounded">
                <h6 class="collapse-header">Login Customer:</h6>
                <a class="collapse-item" href="/KumbiaPHP1/customer">Customer</a>
                <a class="collapse-item" href="/KumbiaPHP1/customer_list">Customer list</a>
            </div>
        </div>
    </li>

    <!-- Nav Item - Pages Collapse Menu -->
    <li class="nav-item active">
        <a class="nav-link" href="#" data-toggle="collapse" data-target="#collapsePages4" aria-expanded="false"
           aria-controls="collapsePages4">
            <i class="fas fa-fw fa-folder"></i>
            <span>Film</span>
        </a>
        <div id="collapsePages4" class="collapse" aria-labelledby="headingPages"
             data-parent="#accordionSidebar">
            <div class="bg-white py-2 collapse-inner rounded">
                <a class="collapse-item" href="/KumbiaPHP1/film">Film</a>
                <a class="collapse-item" href="/KumbiaPHP1/film_actor">Film actor</a>
                <a class="collapse-item" href="/KumbiaPHP1/film_category">Film category</a>
                <a class="collapse-item" href="/KumbiaPHP1/film_list">Film list</a>
                <a class="collapse-item" href="/KumbiaPHP1/film_text">Film text</a>
            </div>
        </div>
        <!-- Nav Item - Pages Collapse Menu -->
    <li class="nav-item active">
        <a class="nav-link" href="#" data-toggle="collapse" data-target="#collapsePages5" aria-expanded="false"
           aria-controls="collapsePages5">
            <i class="fas fa-fw fa-folder"></i>
            <span>Staff</span>
        </a>
        <div id="collapsePages5" class="collapse" aria-labelledby="headingPages"
             data-parent="#accordionSidebar">
            <div class="bg-white py-2 collapse-inner rounded">
                <a class="collapse-item" href="/KumbiaPHP1/staff">Staff</a>
                <a class="collapse-item" href="/KumbiaPHP1/staff_list">Staff list</a>
            </div>
        </div>
<!-- Nav Item - Charts -->
<li class="nav-item">
    <a class="nav-link" href="/KumbiaPHP1/category">
        <i class="fas fa-fw fa-chart-area"></i>
        <span>Category</span></a>
</li>

<!-- Nav Item - Tables -->
<li class="nav-item">
    <a class="nav-link" href="/KumbiaPHP1/inventory">
        <i class="fas fa-fw fa-table"></i>
        <span>Inventory</span></a>
</li>
    <!-- Nav Item - Tables -->
    <li class="nav-item">
        <a class="nav-link" href="/KumbiaPHP1/languaje">
            <i class="fas fa-fw fa-table"></i>
            <span>Language</span></a>
    </li>
    <!-- Nav Item - Tables -->
    <li class="nav-item">
        <a class="nav-link" href="/KumbiaPHP1/payment">
            <i class="fas fa-fw fa-table"></i>
            <span>Payment</span></a>
    </li>
    <!-- Nav Item - Tables -->
    <li class="nav-item">
        <a class="nav-link" href="/KumbiaPHP1/rental">
            <i class="fas fa-fw fa-table"></i>
            <span>Rental</span></a>
    </li>
    <!-- Nav Item - Tables -->
    <li class="nav-item">
        <a class="nav-link" href="/KumbiaPHP1/store">
            <i class="fas fa-fw fa-table"></i>
            <span>Store</span></a>
    </li>

<!-- Divider -->
<hr class="sidebar-divider d-none d-md-block">

<!-- Sidebar Toggler (Sidebar) -->
<div class="text-center d-none d-md-inline">
    <button class="rounded-circle border-0" id="sidebarToggle"></button>
</div>

</ul>