<h1>Modificar Actores: <?= $actor->first_name ?> </h1>
<?php View::content() ?>
<br>
<center>
<form class="form-group" method="post">
    <div class="mb-3">
        <label class="form-label">NOMBRE (S):</label>
        <?= Form::text('actor.first_name', array("class" => "form-control") ) ?>
    </div>
    <div class="mb-3">
        <label class="form-label">APELLIDOS:</label>
        <?= Form::text('actor.last_name', array("class" => "form-control") ) ?>
    </div>
    <br><br>
    <button type="submit" class="btn btn-primary">Guardar</button>
    <a><?php echo Html::linkAction('index', 'Volver', 'title="Volver" class="btn btn-primary" ') ?></a>
</form>
</center>