<h1>Registro de actores: </h1>
<?php View::content() ?>
<center>
<form class="form-group" method="post">
    <div class="mb-3">
        <label class="form-label">NOMBRE:</label>
        <input type="text" class="form-control"   name="actor[first_name]">
    </div>
    <br>
    <div class="mb-3">
        <label class="form-label">APELLIDOS:</label>
        <input type="text" class="form-control" name="actor[last_name]">
    </div>

    <br><br>
    <button type="submit" class="btn btn-primary">SAVE</button>
    <a><?php echo Html::linkAction('index', 'GO BACK', 'title="Volver" class="btn btn-primary" ') ?></a>
</form>
</center>