<style></style>
<body class="bg-custom">
<div class="container" >
    <?php foreach ($customer as $cu):?>
    <div class="row" style=" padding: 10px; border-bottom: 5px solid #486DDA;">
        <div class="col-4">
            <h1 class="text-BLACK">CUSTOMER:</h1>
        </div>
        <div class="col-6 text-center "><h1 class="text-success-emphasis">
                <I><?=$customer[0]->completeName()?></I>
            </h1></div>
    </div>
    <?php endforeach; ?>
    <br><BR>
    <div class="row" >
        <div class="col-2" >
            <img src="https://images.vexels.com/media/users/3/135247/isolated/preview/e70a6296c2a79dc7a56ab05b103f38e8-user-sign-with-background-by-vexels.png" alt="Imagen" class="img-thumbnail" style="width:200px;height:200px;">
        </div>
        <div class="col-6" >
            <?php foreach ($customer as $cu):?>
            <ul class="list-group" >
                <li class="list-group-item d-flex justify-content-between align-items-center list-custom" style="background-color: #486DDA"><BR><B>INFORMATION</B><BR></li>
                <li class="list-group-item d-flex justify-content-between align-items-center" style="background-color: #F2F2F2;">EMAIL:<b><?= $cu->email?></b></li>
                <li class="list-group-item d-flex justify-content-between align-items-center" style="background-color: #F2F2F2;">CELLPHONE:<b><?= $cu->getAddress()->phone?></b></li>
                <li class="list-group-item d-flex justify-content-between align-items-center" style="background-color: #F2F2F2;">ACTIVE:<b><?= $cu->active?></b></li>
                <li class="list-group-item d-flex justify-content-between align-items-center" style="background-color: #F2F2F2;">DATE REGISTRER:<b><?= $cu->create_date?></b></li>
            </ul>
            <?php endforeach; ?>
        </div>

        <div class="col" >
            <?php foreach ($customer as $cu):?>
            <ul class="list-group" >
                <li class="list-group-item d-flex justify-content-between align-items-md-center list-group-item-success" style="background-color: #486DDA"><BR><B>ADDRESS</B><BR></li>
                <li class="list-group-item d-flex justify-content-between align-items-center" style="background-color: #F2F2F2;">ADDRESS:<b><?= $cu->getAddress()->address1?></b> </li>
                <li class="list-group-item d-flex justify-content-between align-items-center" style="background-color: #F2F2F2;">POSTAL CODE:<b><?= $cu->getAddress()->postal_code?></b></li>
                <li class="list-group-item d-flex justify-content-between align-items-center" style="background-color: #F2F2F2;">DISTRIC:<b><?= $cu->getAddress()->district?></b></li>
                <li class="list-group-item d-flex justify-content-between align-items-center" style="background-color: #F2F2F2;">CITY:</b></li>
            </ul>
            <?php endforeach; ?>
        </div>
    </div>
    <BR>
    <div class="row">
        <div class="col-6 " >
            <ul class="list-group" >
                <li class="list-group-item d-flex justify-content-between align-items-center list-group-item-success" style="background-color: #486DDA"><BR><B>MOVIES PAID</B><BR></li>
                
                <?php foreach ($rTotalRentas1 as $uno): ?>
                    <?php if ($uno != null): ?>
                        <li class="list-group-item d-flex justify-content-between align-items-center" style="background-color: #F2F2F2;">Store: Universidad <?= $uno?></li>
                    <?php endif; ?>
                <?php endforeach; ?> 
                    
                <?php foreach ($rTotalRentas2 as $dos): ?>
                    <?php if ($dos != null): ?>
                        <li class="list-group-item d-flex justify-content-between align-items-center" style="background-color: #F2F2F2;">Store: Tecnologico <?= $dos?></li>
                    <?php endif; ?>
                <?php endforeach; ?> 
                    
                <?php foreach ($rTotalRentas as $total): ?>
                    <?php if ($total != null): ?>
                        <li class="list-group-item d-flex justify-content-between align-items-center" style="background-color: #F2F2F2;">Total: <?= $total?></li>
                    <?php endif; ?>
                <?php endforeach; ?>
                </ul>
            <br>
        </div>

        
    <div class="col">
    </div>
    <div class="col-5">
        <div id="carouselExampleFade" class="carousel slide carousel-fade" data-bs-ride="carousel" data-bs-interval="2000">
            <div class="carousel-inner">
                <div class="carousel-item active">
                    <img src="https://e00-elmundo.uecdn.es/assets/multimedia/imagenes/2022/07/30/16591757825079.jpg" class="d-block w-150" alt="..." height="250">
                </div>
                <div class="carousel-item">
                    <img src="https://www.gndiario.com/sites/default/files/noticias/mejores-peliculas-2022%20%281%29.jpg" class="d-block w-150" alt="..." height="250">
                </div>
                <div class="carousel-item">
                    <img src="https://www.unionguanajuato.mx/wp-content/uploads/2022/07/thor-amor-y-trueno.jpg" class="d-block w-150" alt="..." height="250">
                </div>
                <div class="carousel-item">
                    <img src="https://www.hollywoodreporter.com/wp-content/uploads/2022/11/Puss-in-Boots-The-Last-Wish-Everett-H-2022.jpg?w=1296" class="d-block w-150" alt="..." height="250">
                </div>
            </div>
            
            <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleFade" data-bs-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Previous</span>
            </button>
            <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleFade" data-bs-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Next</span>
            </button>
        
    </div>
    <br>
    
<div class="col-2">
    </div>
</div>
<div class="col-12 h-auto">
<li class="list-group-item d-flex justify-content-between align-items-center list-group-item-success" style="background-color: #486DDA">
    <h6 class="mx-auto text-center"><strong>5 MOST VIEWED MOVIES</strong></h6>
  </li>
    <div class="row">
        <div class="col mx-0">
            <ul class="list-group w-auto py-0">
                <li class="list-group-item d-flex justify-content-between align-items-center mb-0" style="background-color: #F2F2F2;"><b>Titulo</b></li>
                <?php foreach ($tfilmcostumer as $fc): ?>
                    <?php if ($fc != null): ?>
                        <li class="list-group-item d-flex justify-content-between align-items-center mb-0"><?= $fc->title ?></li>
                    <?php endif; ?>
                <?php endforeach; ?>
            </ul>
        </div>
        <div class="col mx-0">
            <ul class="list-group w-auto py-0">
                <li class="list-group-item d-flex justify-content-between align-items-center mb-0" style="background-color: #F2F2F2;"><b>Dia de la renta</b></li>
                <?php foreach ($tfilmcostumer as $fc): ?>
                    <?php if ($fc != null): ?>
                        <li class="list-group-item d-flex justify-content-between align-items-center mb-0"><?= $fc->rental_date ?></li>
                    <?php endif; ?>
                <?php endforeach; ?>
            </ul>
        </div>
        <div class="col mx-0">
            <ul class="list-group w-auto py-0">
                <li class="list-group-item d-flex justify-content-between align-items-center mb-0" style="background-color: #F2F2F2;"><b>Dia de la devolución</b></li>
                <?php foreach ($tfilmcostumer as $fc): ?>
                    <?php if ($fc != null): ?>
                        <li class="list-group-item d-flex justify-content-between align-items-center mb-0"><?= $fc->return_date ?></li>
                    <?php endif; ?>
                <?php endforeach; ?>
            </ul>
        </div>
    </div>
</div>

<br>
</div><!-- DIV FINAL -->