<div class="col-4">
    <div id="carouselExampleTouch" class="carousel slide" data-mdb-touch="TRUE">
        <div class="carousel-indicators">
            <button type="button" data-mdb-target="#carouselExampleTouch" data-mdb-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
            <button type="button" data-mdb-target="#carouselExampleTouch" data-mdb-slide-to="1" aria-label="Slide 2"></button>
            <button type="button" data-mdb-target="#carouselExampleTouch" data-mdb-slide-to="2" aria-label="Slide 3"></button>
        </div>
        <div class="carousel-inner">
            <div class="carousel-item active">
                <img src="https://images.firstpost.com/wp-content/uploads/2017/09/it.jpg" class="img-fluid" alt="Wild Landscape" style="max-width: 500px;">

                <div class="carousel-caption d-none d-md-block">
                    <h5><i>IT</i></h5>
                    <p>It Chapter Two is a 2019 American supernatural horror film directed by Andy Muschietti from a screenplay by Gary Dauberman. </p>
                </div>
            </div>
            <div class="carousel-item">
                <img src="https://www.movieberry.com/static/photos/652/65_midi.jpg" class="d-block w-80" alt="Camera">
                <div class="carousel-caption d-none d-md-block">
                    <h5>MEAN GIRLS</h5>
                    <p>Cady Heron tries to adjust to high school life, but when she falls for the ex-boyfriend of the most popular girl downtown, things get tough.</p>
                </div>
            </div>
            <div class="carousel-item">
                <img src="http://images2.fanpop.com/image/photos/12400000/Spirit-Stallion-of-the-Cimarron-spirit-stallion-of-the-cimarron-12421822-1280-960.jpg" class="d-block w-80" alt="Exotic Fruits">
                <div class="carousel-caption d-none d-md-block">
                    <h5>SPIRIT</h5>
                    <p>A wild horse is captured by humans and slowly loses the will to resist training, yet throughout his fight for freedom he refuses to give up hope of one day returning to his herd.</p>
                </div>
            </div>
        </div>
        <button class="carousel-control-prev" type="button" data-mdb-target="#carouselExampleTouch" data-mdb-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-mdb-target="#carouselExampleTouch" data-mdb-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Next</span>
        </button>
    </div>
</div>