<h1>Registro CATEGORY: </h1>
<?php View::content() ?>
<center>
    <form class="form-group" method="post">
        <div class="mb-3">
            <label class="form-label">CATEGORY:</label>
            <input type="text" class="form-control"   name="category[name]">
        </div>
        <br><br>
        <center>
            <button type="submit" class="btn btn-primary">Guardar</button>
            <a><?php echo Html::linkAction('index', 'Volver', 'title="Volver" class="btn btn-primary" ') ?></a>
        </center>

    </form>
</center>