<h1>MODIFY RENTAL: <?= $rental->id ?> </h1>
<?php View::content() ?>
<br>
<center>
<form class="form-group" method="post">

    <div class="mb-3">
        <label class="form-label">RENTAL DATE:</label>
        <?= Form::date('rental.rental_date', array("class" => "form-control") ) ?>
    </div>
    <div class="mb-3">
        <label class="form-label">INVENTORY ID:</label>
        <?= Form::number('rental.inventory_id', array("class" => "form-control") ) ?>
    </div>
    <div class="mb-3">
        <label class="form-label">CUSTOMER ID:</label>
        <?= Form::number('rental.customer_id', array("class" => "form-control") ) ?>
    </div>
    <div class="mb-3">
        <label class="form-label">RETURN DATE:</label>
        <?= Form::date('rental.return_date', array("class" => "form-control") ) ?>
    </div>
    <div class="mb-3">
        <label class="form-label">STAFF ID:</label>
        <?= Form::number('rental.staff_id', array("class" => "form-control") ) ?>
    </div>


    <br><br>
    <button type="submit" class="btn btn-primary">SAVE</button>
    <a><?php echo Html::linkAction('index', 'GO BACK', 'title="Volver" class="btn btn-primary" ') ?></a>
</form>
</center>