<h1>Nueva Lista de Peliculas</h1>
<?php View::content(); ?>
<form method="post">
    <div class="row g-3">
        <div class="col-sm-6">
            <label for="title" class="form-label">Titulo</label>
            <input type="text" name="film_list[title]" class="form-control" id="title">
        </div>

        <div class="col-sm-6">
            <label for="description" class="form-label">Descripción</label>
            <input type="text" name="film_list[description]" class="form-control" id="description">
        </div>

        <div class="col-sm-6">
            <label for="category" class="form-label">Categoria</label>
            <input type="text" name="film_list[category]" class="form-control" id="category">
        </div>

        <div class="col-sm-6">
            <label for="price" class="form-label">Precio</label>
            <input type="number" name="film_list[price]" class="form-control" id="price">
        </div>

        <div class="col-sm-6">
            <label for="length" class="form-label">Longitud</label>
            <input type="number" name="film_list[length]" class="form-control" id="length">
        </div>

        <div class="col-sm-6">
            <label for="rating" class="form-label">Clasificación</label>
            <input type="text" name="film_list[rating]" class="form-control" id="rating">
        </div>

        <div class="col-sm-6">
            <label for="actors" class="form-label">Actores</label>
            <input type="text" name="film_list[actors]" class="form-control" id="actors">
        </div>

    </div>
    <br>
    <div class="row mt-1">
        <div class="col-6">
            <button class=" btn btn-primary " type="submit">GUARDAR</button>
        </div>
    </div>
</form>
