<style>
    table {
        border-collapse: collapse;
        width: 100%;
    }
    th, td {
        text-align: center;
        padding: 8px;
    }
    tr:nth-child(even) {
        background-color: rgba(150, 212, 212, 0.4);
    }
</style>
<BR>
<h1>LANGUAGE: </h1>
<br>
<?php View::content(); ?>
<br>
<center>
    <table >
        <thead>
        <tr>
            <th> ID </th>
            <th>NAME</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($languaje as $la):?>
            <tr>
                <td><?= $la->id?></td>
                <td><?= $la->name?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
    <br><br>
    <a><?php echo Html::linkAction('registro', 'TO REGISTER', 'title="registro" class="btn btn-primary" ') ?></a>
    <a>  </a>
    <a><?php echo Html::linkAction('modificar', 'MODIFY', 'title="modificar" class="btn btn-primary" ') ?></a>
</center>


