<h1>MODIFY LANGUAJE: <?= $languaje->id ?> </h1>
<?php View::content() ?>
<br>
<center>
<form class="form-group" method="post">

    <div class="mb-3">
        <label class="form-label">NAME:</label>
        <?= Form::text('languaje.name', array("class" => "form-control") ) ?>
    </div>
    <br><br>
    <button type="submit" class="btn btn-primary">SAVE</button>
    <a><?php echo Html::linkAction('index', 'GO BACK', 'title="Volver" class="btn btn-primary" ') ?></a>
</form>
</center>