<h1>LANGUAGE RECORD: </h1>
<?php View::content() ?>
<center>
<form class="form-group" method="post">
    <div class="mb-3">
        <label class="form-label">NAME:</label>
        <input type="text" class="form-control"   name="languaje[name]">
    </div>

    <br><br>
    <button type="submit" class="btn btn-primary">SAVE</button>
    <a><?php echo Html::linkAction('index', 'GO BACK', 'title="GO BACK" class="btn btn-primary" ') ?></a>
</form>
</center>