<!DOCTYPE html>
<html lang="es">
<head>
	<meta charset="<?= APP_CHARSET ?>" >
	<title>KumbiaPHP web &amp; app Framework</title>
	<link rel="stylesheet" href="<?= PUBLIC_PATH ?>css/style.css" >
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css">
</head>
<body>
	<?php View::content() ?> 
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>
