<h1>PRODUCTOS: </h1>
<BR>
<table border="1">
    <thead>
    <tr>
        <th> ID </th>
        <th>NOMBRE</th>
        <th>DESCRIPCION</th>
        <th>PRECIO COMPRA</th>
        <th>PRECIO VENTA</th>
        <th>UTILIDAD</th>
        <th>CREATED_IN</th>
        <th>UPDATED_IN</th>
    </tr>
    </thead>
    <tbody>
    <!-- nombre y siempre la variable va la primera letra de la variable -->
    <?php foreach ($productos as $p):?>
        <tr>
            <td><?= $p->id?></td>
            <td><?= $p->nombre?></td>
            <td><?= $p->descripcion?></td>
            <td><?= $p->precio_compra?></td>
            <td><?= $p->precio_venta?></td>
            <td><?= $p->utilidad?></td>
            <td><?= $p->created_at?></td>
            <td><?= $p->updated_in?></td>
        </tr>
    <?php endforeach; ?>

    </tbody>
    <tfoot>
    <tr>
        <td colspan="7" align="center">Pie de pagina</td>
    </tr>
    </tfoot>
</table>