<h1>Registro de productos:</h1>
<?php View::content() ?>

<form class="form-group" method="post">
    <div class="mb-3">
        <label class="form-label">Nombre:</label>
        <input type="text" class="form-control"   name="productos[nombre]">
    </div>
    <div class="mb-3">
        <label class="form-label">Descripcion:</label>
        <input type="text" class="form-control" name="productos[descripcion]">
    </div>
    <div class="mb-3">
        <label class="form-label">Precio de compra:</label>
        <input type="number" class="form-control" name="productos[precio_compra]">
    </div>
    <div class="mb-3">
        <label class="form-label">Precio de venta:</label>
        <input type="number" class="form-control" name="productos[precio_venta]">
    </div>
    <div class="mb-3">
        <label class="form-label">Utilidad:</label>
        <input type="number" class="form-control" name="productos[utilidad]">
    </div>

    <button type="submit" class="btn btn-primary">Guardar</button>
</form>