<h1> Información Actor</h1>
<table border="1">
    <thead>
    <tr>
        <th>ID</th>
        <th>Nombre</th>
        <th>Apellido</th>
        <th>Información Pelicula</th>
        <th>Creado</th>
        <th>Actualizado</th>
    </tr>
    </thead>
    <?php foreach ($actorinfo as $a): ?>
    <tbody>
    <tr>
        <td> <?= $a->id ?></td>
        <td><?= $a->first_name ?></td>
        <td><?= $a->last_name ?></td>
        <td><?= $a->film_info ?></td>
        <td><?= $a->updated_id ?></td>
        <td><?= $a->created_at ?></td>
    </tr>
    <?php endforeach; ?>
    </tbody>
    <tfoot>
    <tr>
        <td colspan="5" align="center">Pie de pagina</td>
    </tr>
    </tfoot>
</table>