<h1>Nuevo Actor</h1>
<?php View::content() ?>

<form class="form-group" method="post">

    <div class="mb-3">
        <label class="form-label">Nombre</label>
        <input type="text" class="form-control"   name="actor_info[first_name]">
    </div>
    <div class="mb-3">
        <label class="form-label">Apellido</label>
        <input type="text" class="form-control"   name="actor_info[last_name]">
    </div>
    <div class="mb-3">
        <label class="form-label">Información Pelicula</label>
        <input type="text" class="form-control"  name="actor_info[film_info]">
    </div>

    </br>
    <button type="submit" class="btn btn-primary">Guardar</button>
</form>