<h1>Registro de actores: </h1>
<?php View::content() ?>
<center>
    <form class="form-group" method="post">
        <div class="mb-3">
            <label class="form-label">COUNTRY:</label>
            <input type="text" class="form-control"   name="country[country]">
        </div>


        <br><br>
        <button type="submit" class="btn btn-primary">Guardar</button>
        <a><?php echo Html::linkAction('index', 'Volver', 'title="Volver" class="btn btn-primary" ') ?></a>
    </form>
</center>