<h1>Modificar Actores: <?= $city->id ?> </h1>
<?php View::content() ?>
<br>
<center>
    <form class="form-group" method="post">
        <div class="mb-3">
            <label class="form-label">CITY:</label>
            <?= Form::text('city.city', array("class" => "form-control") ) ?>
        </div>
        <div class="mb-3">
            <label class="form-label">COUNTRY ID:</label>
            <?= Form::text('city.country_id', array("class" => "form-control") ) ?>
        </div>
        <br><br>
        <button type="submit" class="btn btn-primary">SAVE</button>
        <a><?php echo Html::linkAction('index', 'GO BACK', 'title="Volver" class="btn btn-primary" ') ?></a>
    </form>
</center>