<br>
<h1>City registration: </h1>
<?php View::content() ?>
<center>
    <form class="form-group" method="post">
        <div class="mb-3">
            <label class="form-label">CITY:</label>
            <input type="text" class="form-control"   name="city[city]">
        </div>
        <br>
        <div class="mb-3">
            <label class="form-label">ID COUNTRY:</label>
            <input type="text" class="form-control" name="city[country_id]">
        </div>
        <br><br>
        <button type="submit" class="btn btn-primary">SAVE</button>
        <a><?php echo Html::linkAction('index', 'GO BACK', 'title="Volver" class="btn btn-primary" ') ?></a>
    </form>
</center>