<h1>FILM TEXT INFO</h1>
<table class="table table-dark table-striped">
    <thead>
        <tr>
            <th>FILM ID</th>
            <th>TITLE</th>
            <th>DESCRIPTION</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td><?= $filmtext->film_id ?></td>
            <td><?= $filmtext->title ?></td>
            <td><?= $filmtext->description ?></td>
        </tr>
    </tbody>
</table>