<!DOCTYPE html>
<html lang="es">
 <head>
  <meta charset=<?= APP_CHARSET ?> >
  <title>KumbiaPHP Framework</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
  <link rel="stylesheet" href="/KumbiaPHP1/libs/ample/css/sb-admin-2.min.css">
  <link href="/KumbiaPHP1/libs/ample/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">
  <?= Html::includeCss() ?>
  <script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.4/dist/Chart.min.js"></script>
</head>

<body id="page-top>
<div class="container">
    <header class="row">
    </header>
    <?php //View::content() ?>
    <?php //View::partial('kumbia/footer') ?>
    <!-- Page Wrapper -->
    <div id="wrapper">
    <?php View::partial('ample/sidebar') ?>
    <!-- Content Wrapper -->
    <div id="content-wrapper" class="d-flex flex-column">
        <!-- Main Content -->
        <div id="content">
        <?php View::partial('ample/topbar') ?> 
        <?php View::partial('ample/container') ?> 
        </div>
    </div>
    </div>

    
    <!-- Bootstrap core JavaScript-->
    <script src="/KumbiaPHP1/libs/ample/vendor/jquery/jquery.min.js"></script>
    <script src="/KumbiaPHP1/libs/ample/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Core plugin JavaScript-->
    <script src="/KumbiaPHP1/libs/ample/vendor/jquery-easing/jquery.easing.min.js"></script>

    <!-- Custom scripts for all pages-->
    <script src="/KumbiaPHP1/libs/ample/js/sb-admin-2.min.js"></script>

</div>

</body>
</html>