<h1>MODIFY STAFF LIST</h1>
<?php View::content(); ?>
<form method="post">
    <div class="row g-3">
        <div class="col-sm-6">
            <label for="category_id" class="form-label">NAME:</label>
            <input type="text" name="staff_list[name]" class="form-control" id="category_id" placeholder=""
                   value="<?= $staff_list ->staff_id?>" required="">
        </div>
        <div class="col-sm-6">
            <label for="category_id" class="form-label">ADDRESS:</label>
            <input type="text" name="staff_list[address]" class="form-control" id="category_id" placeholder=""
                   value="<?= $staff_list ->staff_id?>" required="">
        </div>
        <div class="col-sm-6">
            <label for="category_id" class="form-label">ZIP CODE:</label>
            <input type="text" name="staff_list[zip_code]" class="form-control" id="category_id" placeholder=""
                   value="<?= $staff_list ->staff_id?>" required="">
        </div>
        <div class="col-sm-6">
            <label for="category_id" class="form-label">PHONE:</label>
            <input type="text" name="staff_list[phone]" class="form-control" id="category_id" placeholder=""
                   value="<?= $staff_list ->staff_id?>" required="">
        </div>
        <div class="col-sm-6">
            <label for="category_id" class="form-label">CITY:</label>
            <input type="text" name="staff_list[city]" class="form-control" id="category_id" placeholder=""
                   value="<?= $staff_list ->staff_id?>" required="">
        </div>
        <div class="col-sm-6">
            <label for="category_id" class="form-label">COUNTRY:</label>
            <input type="text" name="staff_list[country]" class="form-control" id="category_id" placeholder=""
                   value="<?= $staff_list ->staff_id?>" required="">
        </div>

    </div>
    <br>
    <div class="row mt-1">
        <div class="col-6">
            <br><br>
            <button type="submit" class="btn btn-primary">SAVE</button>
            <a><?php echo Html::linkAction('index', 'GO BACK', 'title="Volver" class="btn btn-primary" ') ?></a>
        </div>
    </div>
</form>