<h1>MODIFICAR: <?= $film->title ?> </h1>
<center>
    <form class="form-group" method="post">
        <div class="mb-3">
            <label class="form-label">Titulo</label>
            <?= Form::text('film.title', array("class" => "form-control")) ?>
        </div>
        <div class="mb-3">
            <label class="form-label">Descripciones</label>
            <?= Form::text('film.description', array("class" => "form-control")) ?>
        </div>
        <div class="mb-3">
            <label class="form-label">Año de lanzamiento</label>
            <?= Form::text('film.release_year', array("class" => "form-control")) ?>
        </div>
        <div class="mb-3">
            <label class="form-label">Lenguajes</label>
            <?= Form::text('film.language', array("class" => "form-control")) ?>
        </div>
        <div class="mb-3">
            <label class="form-label">Lenguaje original</label>
            <?= Form::text('film.original_language', array("class" => "form-control")) ?>
        </div>
        <div class="mb-3">
            <label class="form-label">Duracion (mins) </label>
            <?= Form::text('film.length', array("class" => "form-control")) ?>
        </div>
        <div class="mb-3">
            <label class="form-label">Costo de produccion</label>
            <?= Form::text('film.replacement_cost', array("class" => "form-control")) ?>
        </div>
        <div class="mb-3">
            <label class="form-label">Clasificacion</label>
            <?= Form::text('film.rating', array("class" => "form-control")) ?>
        </div>
        <div class="mb-3">
            <label class="form-label">Caracteriscas especiales</label>
            <?= Form::text('film.special_features', array("class" => "form-control")) ?>
        </div>
        <button type="submit" class="btn btn-primary">Guardar</button>
        <a href="../index" class="btn btn-danger">Volver</a>
    </form>
</center>