<h1>MODIFY STORE: <?= $store->id ?> </h1>
<?php View::content() ?>
<br>
<center>
<form class="form-group" method="post">

    <div class="mb-3">
        <label class="form-label">MANAGER STAFF ID:</label>
        <?= Form::NUMBER('store.manager_staff_id', array("class" => "form-control") ) ?>
    </div>
    <br>

    <div class="mb-3">
        <label class="form-label">ADDRESS ID:</label>
        <?= Form::number('store.address_id', array("class" => "form-control") ) ?>
    </div>
    <br>

    <div class="mb-3">
        <label class="form-label">NAME:</label>
        <?= Form::text('store.nombre', array("class" => "form-control") ) ?>
    </div>

    <br><br>
    <button type="submit" class="btn btn-primary">SAVE</button>
    <a><?php echo Html::linkAction('index', 'GO BACK', 'title="Volver" class="btn btn-primary" ') ?></a>
</form>
</center>