<h1>STORE RECORD: </h1>
<?php View::content() ?>
<center>
<form class="form-group" method="post">
    <div class="mb-3">
        <label class="form-label">MANAGER STAFF ID:</label>
        <input type="number" class="form-control"   name="store[manager_staff_id]">
    </div>
    <br>

    <div class="mb-3">
        <label class="form-label">ADDRESS ID:</label>
        <input type="number" class="form-control"   name="store[address_id]">
    </div>
    <br>

    <div class="mb-3">
        <label class="form-label">NAME:</label>
        <input type="text" class="form-control"   name="store[nombre]">
    </div>
    <br>




    <br>
    <button type="submit" class="btn btn-primary">SAVE</button>
    <a><?php echo Html::linkAction('index', 'GO BACK', 'title="GO BACK" class="btn btn-primary" ') ?></a>
</form>
</center>