<style>
    table {
        border-collapse: collapse;
        width: 100%;
    }

    th, td {
        text-align: center;
        padding: 8px;
    }

    tr:nth-child(even) {
        background-color: rgba(150, 212, 212, 0.4);
    }
</style>
<h1>INVENTORY: </h1>
<br>
<?php View::content(); ?>
<br>
<center>
    <table >
        <thead>
        <tr>
            <th> ID </th>
            <th>FILM_ID</th>
            <th>STORE-ID</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($inventory as $in):?>
            <tr>
                <td><?= $in->id?></td>
                <td><?= $in->film_id?></td>
                <td><?= $in->store_id?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
    <br><br>
    <a><?php echo Html::linkAction('registro', 'Registrar', 'title="registro" class="btn btn-primary" ') ?></a>
    <a>  </a>
    <a><?php echo Html::linkAction('modificar', 'Modificar', 'title="modificar" class="btn btn-primary" ') ?></a>
</center>
