<BR>
<h1>INVENTORY REGISTER: </h1>
<?php View::content() ?>
<center>
    <form class="form-group" method="post">
        <div class="mb-3">
            <label class="form-label">FILM ID:</label>
            <input type="text" class="form-control"   name="inventory[film_id]">
        </div>
        <br>
        <div class="mb-3">
            <label class="form-label">STORE ID:</label>
            <input type="text" class="form-control" name="inventory[store_id]">
        </div>

        <br><br>
        <button type="submit" class="btn btn-primary">Guardar</button>
        <a><?php echo Html::linkAction('index', 'Volver', 'title="Volver" class="btn btn-primary" ') ?></a>
    </form>
</center>